from __future__ import annotations

import os
import logging
from pathlib import Path
from typing import List, Union

log = logging.getLogger(__name__)


class ConfigEntryExistsError(Exception):
    pass


class ConfigFileEditor:
    """Edit line-based config files (e.g. /etc/fstab).

    Inserted blocks are wrapped in comment delimiters so they can be
    found, replaced, or removed later without touching surrounding content.
    """

    def __init__(
        self,
        target_file: Union[str, Path],
        base_identifier: str = "",
        comment_char: str = "#",
        source_hint: str = "CONFIG LINES GENERATED BY HSBT SCRIPT",
        create_if_missing: bool = True,
        create_mode: int = 0o660,
    ):
        self.target_file = Path(target_file) if isinstance(target_file, str) else target_file
        self.comment_char = comment_char
        self.base_identifier = base_identifier
        self.source_hint = source_hint
        self.create_if_missing = create_if_missing
        self.create_mode = create_mode

    # ------------------------------------------------------------------
    # Internal file model
    # ------------------------------------------------------------------

    class _File:
        class _Line:
            def __init__(self, content: str, file: "ConfigFileEditor._File"):
                self.content = content
                self.file = file
                self.removed = False

            def remove(self) -> None:
                self.removed = True

            def is_(self, val: str) -> bool:
                return self.content == val

            @property
            def number(self) -> int:
                return self.file.lines.index(self)

            def insert_after(self, lines: Union[str, List[str]]) -> None:
                if not isinstance(lines, list):
                    lines = [lines]
                self.file.insert_lines(lines, self.number + 1)

            def is_last(self) -> bool:
                return self.file.cursor >= len(self.file.lines)

        def __init__(self, path: Path):
            self.path = path
            self.lines: List[ConfigFileEditor._File._Line] = []
            self.cursor: int = 0
            self.current_line: ConfigFileEditor._File._Line = None
            self.record: bool = True

        def read(self) -> None:
            with open(self.path, "r", encoding="utf-8") as f:
                for raw in f.readlines():
                    self.lines.append(ConfigFileEditor._File._Line(raw.strip("\n"), self))
            self.cursor = 0

        def next_line(self) -> "_File._Line":
            if not self.record and self.current_line:
                self.current_line.remove()
            self.current_line = self.lines[self.cursor]
            self.cursor += 1
            return self.current_line

        def insert_line(self, line: Union[str, "_File._Line"], index: int) -> None:
            if isinstance(line, str):
                line = ConfigFileEditor._File._Line(line, self)
            self.lines.insert(index, line)
            self.cursor += 1

        def insert_lines(self, lines: List[Union[str, "_File._Line"]], index: int) -> None:
            for offset, line in enumerate(lines):
                self.insert_line(line, index + offset)

        def attach_lines(self, lines: List[Union[str, "_File._Line"]]) -> None:
            for line in lines:
                self.insert_line(line, len(self.lines))

        def is_empty(self) -> bool:
            return len(self.lines) == 0

        def save(self) -> None:
            with open(self.path, "w", encoding="utf-8") as f:
                f.writelines(line.content + "\n" for line in self.lines if not line.removed)

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def get_config_entry(self, identifier: str) -> List[str]:
        start = self._start_delimiter(identifier)
        end = self._end_delimiter(identifier)
        if not self.target_file.exists():
            return []
        f = self._File(self.target_file)
        f.read()
        if f.is_empty():
            return []
        result = []
        inside = False
        while True:
            line = f.next_line()
            if line.is_(end):
                inside = False
            if inside:
                result.append(line.content)
            if line.is_(start):
                inside = True
            if line.is_last():
                break
        return result

    def set_config_entry(self, content: Union[str, List[str]], identifier: str) -> None:
        self._prepare_target(suppress_create=not bool(content))
        if content and not isinstance(content, list):
            content = [content]
        start = self._start_delimiter(identifier)
        end = self._end_delimiter(identifier)
        f = self._File(self.target_file)
        f.read()
        inserted = False
        if not f.is_empty():
            while True:
                line = f.next_line()
                if line.is_(start):
                    line.remove()
                    f.record = False
                if line.is_(end):
                    line.remove()
                    f.record = True
                    if content:
                        line.insert_after([start] + content + [end])
                    inserted = True
                if line.is_last():
                    break
        if not inserted and content:
            f.attach_lines([start] + content + [end])
        f.save()

    def remove_config_entry(self, identifier: str) -> None:
        self.set_config_entry(content=None, identifier=identifier)

    # ------------------------------------------------------------------
    # Internals
    # ------------------------------------------------------------------

    def _prepare_target(self, suppress_create: bool = False) -> None:
        if self.target_file.is_dir():
            raise ValueError(f"Target {self.target_file} is a directory, expected a file.")
        if self.target_file.is_file():
            if not os.access(self.target_file, os.W_OK):
                raise PermissionError(f"Target file {self.target_file} is not writable.")
        elif not self.target_file.exists():
            if self.create_if_missing and not suppress_create:
                self.target_file.parent.mkdir(exist_ok=True, parents=True, mode=0o755)
                self.target_file.touch(mode=self.create_mode)
            else:
                raise FileNotFoundError(f"Target file {self.target_file} does not exist.")

    def _start_delimiter(self, identifier: str) -> str:
        return f"{self.comment_char} <{self.source_hint} '{self.base_identifier}/{identifier}'>"

    def _end_delimiter(self, identifier: str) -> str:
        return f"{self.comment_char} </{self.source_hint} '{self.base_identifier}/{identifier}'>"
