from enum import Enum


class EnvVarNames(str, Enum):
    CENTRAL_CONFIG_DIR = "HSBT_CENTRAL_CONFIG_DIR"
    CONNECTION_CONFIG_FILE = "HSBT_CONNECTIONS_CONFIG_FILE"
    SSH_KEY_DIRECTORY = "HSBT_SSH_KEY_FILE_DIR"
    PASSWORD = "HSBT_PASSWORD"
    BIN_PATH_RCLONE = "HSBT_BIN_PATH_RCLONE"
    BIN_PATH_SSH = "HSBT_BIN_PATH_RCLONE"
    BIN_PATH_SSHFS = "HSBT_BIN_PATH_SSHFS"
    BIN_PATH_SCP = "HSBT_BIN_PATH_SCP"
    BIN_PATH_SSH_COPY_ID = "HSBT_BIN_PATH_SSH_COPY_ID"


EXECUTABLE_PATH_ENV_VAR_MAPPING = {
    "rclone": EnvVarNames.BIN_PATH_RCLONE,
    "ssh": EnvVarNames.BIN_PATH_SSH,
    "sshfs": EnvVarNames.BIN_PATH_SSHFS,
    "scp": EnvVarNames.BIN_PATH_SCP,
    "ssh-copy-id": EnvVarNames.BIN_PATH_SSH_COPY_ID,
}
